export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_RECEIVED = 'SIGNIN_USER_RECEIVED';
export const SIGNIN_USER_FAILED = 'SIGNIN_USER_FAILED';

export const CREATE_COMPANY = 'CREATE_COMPANY';
export const CREATE_COMPANY_RECEIVED = 'CREATE_COMPANY_RECEIVED';
export const CREATE_COMPANY_FAILED = 'CREATE_COMPANY_FAILED';
